# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33011/project_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: project_blog
mybatis-plus:
  mapper-locations: classpath:/mapper/**Mapper.xml
server:
  port: 33010
